### ISSUE TITLE
Is the useRelayClient hook supported?

### ISSUE THREAD

**Issue by jthcast** [reservoirprotocol/relay-kit#390]
Hello Relay Team! I'm trying to bridge using Relay. However, contrary to the explanation in the Docs, it seems that currently `relay-kit-hooks` does not provide a `useRelayClient` hook. Do you have a support plan?

<img width="763" alt="스크린샷 2024-12-10 오전 11 21 12" src="https://github.com/user-attachments/assets/95a9eba0-8456-4f2c-b190-b5f39b565f5f">

<img width="320" alt="스크린샷 2024-12-10 오전 11 24 11" src="https://github.com/user-attachments/assets/8190cf97-64d7-40c3-9a3e-b7e3c702dd68">

**Comment by pedromcunha** [comment]
Docs are now updated. Thanks for reporting this!
